### ISSUE TITLE
'Module (ZfcUserAdmin) could not be initialized.'

### ISSUE THREAD

**Issue by ghost** [Danielss89/ZfcUserAdmin#10]
Hi,
i've got this error:

Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ZfcUserAdmin) could not be initialized.'

"minimum-stability": "dev",
"require": { 
"danielss89/zfc-user-admin": "dev-master"
},
"repositories": [
{
            "type": "package",
            "package": {
                "version": "dev-master",
                "name": "danielss89/zfc-user-admin",
                "source": {
                    "type": "git",
                    "url": "https://github.com/Danielss89/ZfcUserAdmin.git",
                    "reference": "master"
                } 
            }
        }
   ]
 }

**Comment by ghost** [comment]
Same error by adding into config file :
'module_paths' => array(
                'module',
                'vendor',
                'vendor/danielss89/zfc-user-admin'
        ),

**Comment by Hounddog** [comment]
Am not sure if this issue is still existing as it is quite old. This error mostly happens if you did not register it in the application.config.php. Could you please confirm if i can close this issue?

**Comment by neokeats** [comment]
hi, 
the error is still there
