### ISSUE TITLE
custom user mapper

### ISSUE THREAD

**Issue by jonny-no1** [Danielss89/ZfcUserAdmin#12]
Module.php#74:

if ($mapperClass = 'ZfcUserAdmin\Mapper\UserZendDb') {

shouldn't it rather be

if ($mapperClass == 'ZfcUserAdmin\Mapper\UserZendDb') {

?

**Comment by leup** [comment]
Hi ! Same problem here and I confirm that it should be `if ($mapperClass == 'ZfcUserAdmin\Mapper\UserZendDb')`
