### ISSUE TITLE
create action

### ISSUE THREAD

**Issue by alpigo** [Danielss89/ZfcUserAdmin#19]
When I go to action create there is form with two input fields for email rather than passwords.
And when I create new user, password in database is not encrypted.

**Comment by bartvanenter** [comment]
i have the same problem

**Comment by bartvanenter** [comment]
does anybody have a solution for this?

**Comment by Hounddog** [comment]
the solution is to complete this functionality. i am currently integrating this module into a new project and will most likely fix this in the next few days.
