### ISSUE TITLE
Class 'ZfcUserDoctrineORM\Mapper\User' not found

### ISSUE THREAD

**Issue by marks12** [Danielss89/ZfcUserAdmin#24]
After installing, i have error in url http://......../admin/user/list

Fatal error: Class 'ZfcUserDoctrineORM\Mapper\User' not found in ....\vendor\ZfcUserAdmin\src\ZfcUserAdmin\Mapper\UserDoctrine.php on line 8
install:
1.Clone ZfcUserAdmin
2.Clone ZfcAdmin 
3.Add modules to config

Am i do anything wrong ?

**Comment by alabbas-ali** [comment]
I have the Same problem

**Comment by weeamali** [comment]
I have the Same problem

**Comment by Danielss89** [comment]
Did you install ZfcUserDoctrineORM?

**Comment by alabbas-ali** [comment]
ya i have installed if but unfortunately i haven't work correct for me

**Comment by weeamali** [comment]
Take the world's best courses, online. Coursera envisions a world where 
anyone, anywhere can transform their life by accessing the world’s best 
learning experience.
[Ready to learn something new?]
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjBSd3hodUpERWVXX3NRNXZfaWMxTXciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDgxYjBlODFhNTg2ODc4OGQ2ODc4M2JmMzk4ZjNlODIwNWEzODhlYTBiMDQ5MDM5MmNmMDAwMDAwMDExMTNhMzhlNTkyYTE2OWNlMDBiNGNmMzZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uMFJ3eGh1SkRFZVdfc1E1dl9pYzFNdyJ9fSwidXNlcklkIjotMX0.kKkt2t2qMiFoM5a95JHcDbEuOtQzYXQtU0ohdcBZHIQ> 	
My Courses
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjBSd3hodUpERWVXX3NRNXZfaWMxTXciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDgxYjBlODFhNTg2ODc4OGQ2ODc4M2JmMzk4ZjNlODIwNWEzODhlYTBiMDQ5MDM5MmNmMDAwMDAwMDExMTNhMzhlNTkyYTE2OWNlMDBiNGNmMzZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uMFJ3eGh1SkRFZVdfc1E1dl9pYzFNdyJ9fSwidXNlcklkIjotMX0.kKkt2t2qMiFoM5a95JHcDbEuOtQzYXQtU0ohdcBZHIQ> 
Course Catalog
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvY291cnNlcz91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by4wUnd4aHVKREVlV19zUTV2X2ljMU13IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA4MWIwZTgxYTU4Njg3ODhkNjg3ODNiZjM5OGYzZTgyMDVhMzg4ZWEwYjA0OTAzOTJjZjAwMDAwMDAxMTEzYTM4ZTU5MmExNjljZTAwYjRjZjM2QHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLjBSd3hodUpERWVXX3NRNXZfaWMxTXcifX0sInVzZXJJZCI6LTF9.b-bI5-_Km7t84BMiKiSsGCM3vHaqn-ukeFgZqfQ2Dy8>


Alabbas Alhaj Ali thinks you'll love learning on Coursera

We envision a world where anyone, anywhere can transform their life by 
accessing the world’s best learning experience. We offer hundreds open 
online courses, in dozens of subject areas, all from top universities and 
institutions.

Course topics range from business and management, to computer science, to 
medicine, music, education, and more.

Millions of our learners have advanced their careers, discovered new 
passions, and built lasting friendships through their Coursera courses. We 
hope you'll join us in learning without limits!

The Coursera Team

Explore Coursera
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvb25ib2FyZGluZy8_dG9rZW49YjQwNGRjNDlkYjdiOWY1MTJkZDgyNGZjMjM3NDAyODkmZW1haWw9cmVwbHkrMDA4MWIwZTgxYTU4Njg3ODhkNjg3ODNiZjM5OGYzZTgyMDVhMzg4ZWEwYjA0OTAzOTJjZjAwMDAwMDAxMTEzYTM4ZTU5MmExNjljZTAwYjRjZjM2QHJlcGx5LmdpdGh1Yi5jb20mbmFtZT1EYW5pZWxzczg5L1pmY1VzZXJBZG1pbj91dG1fbWVkaXVtPWVtYWlsJnV0bV9zb3VyY2U9aW52aXRhdGlvbnMmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by4wUnd4aHVKREVlV19zUTV2X2ljMU13IiwidHJhY2tpbmciOnsidXNlcklkIjotMSwidXNlckVtYWlsIjoicmVwbHkrMDA4MWIwZTgxYTU4Njg3ODhkNjg3ODNiZjM5OGYzZTgyMDVhMzg4ZWEwYjA0OTAzOTJjZjAwMDAwMDAxMTEzYTM4ZTU5MmExNjljZTAwYjRjZjM2QHJlcGx5LmdpdGh1Yi5jb20iLCJub3RpZmljYXRpb25UeXBlIjoiZ3Jvd3RoLmludml0YXRpb24iLCJjYW1wYWlnbklkIjoibm90aWZpY2F0aW9ucy5hdXRvLjBSd3hodUpERWVXX3NRNXZfaWMxTXcifX0sInVzZXJJZCI6LTF9.btf4NUhIVq8dBOlQtce_SYbaabYAM-Cx4EPWlrTsy_4>
Download our App:  iOS
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2l0dW5lcy5hcHBsZS5jb20vYXBwL2FwcGxlLXN0b3JlL2lkNzM2NTM1OTYxP2N0PU1vYmlsZSUyMFByb21vJTIwRW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZtdD04JnB0PTIzMzQxNTAmdXRtX2NhbXBhaWduPW5vdGlmaWNhdGlvbnMuYXV0by4wUnd4aHVKREVlV19zUTV2X2ljMU13JnV0bV9tZWRpdW09ZW1haWwiLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDgxYjBlODFhNTg2ODc4OGQ2ODc4M2JmMzk4ZjNlODIwNWEzODhlYTBiMDQ5MDM5MmNmMDAwMDAwMDExMTNhMzhlNTkyYTE2OWNlMDBiNGNmMzZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uMFJ3eGh1SkRFZVdfc1E1dl9pYzFNdyJ9fSwidXNlcklkIjotMX0.I4meIMitIWbVtsVSRMpWpfo_ZSPylvJVuU3gQUmQVtw> 
  |  Android
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3BsYXkuZ29vZ2xlLmNvbS9zdG9yZS9hcHBzL2RldGFpbHM_aWQ9b3JnLmNvdXJzZXJhLmFuZHJvaWQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uMFJ3eGh1SkRFZVdfc1E1dl9pYzFNdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwODFiMGU4MWE1ODY4Nzg4ZDY4NzgzYmYzOThmM2U4MjA1YTM4OGVhMGIwNDkwMzkyY2YwMDAwMDAwMTExM2EzOGU1OTJhMTY5Y2UwMGI0Y2YzNkByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by4wUnd4aHVKREVlV19zUTV2X2ljMU13In19LCJ1c2VySWQiOi0xfQ.02Ok5_PFxWa1DC2Tf8Pen4qdE-WP-IN8hyYS3hbsRWo>
Learner Help Center
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL2xlYXJuZXIuY291cnNlcmEuaGVscC8_dXRtX21lZGl1bT1lbWFpbCZ1dG1fc291cmNlPWludml0YXRpb25zJnV0bV9jYW1wYWlnbj1ub3RpZmljYXRpb25zLmF1dG8uMFJ3eGh1SkRFZVdfc1E1dl9pYzFNdyIsInRyYWNraW5nIjp7InVzZXJJZCI6LTEsInVzZXJFbWFpbCI6InJlcGx5KzAwODFiMGU4MWE1ODY4Nzg4ZDY4NzgzYmYzOThmM2U4MjA1YTM4OGVhMGIwNDkwMzkyY2YwMDAwMDAwMTExM2EzOGU1OTJhMTY5Y2UwMGI0Y2YzNkByZXBseS5naXRodWIuY29tIiwibm90aWZpY2F0aW9uVHlwZSI6Imdyb3d0aC5pbnZpdGF0aW9uIiwiY2FtcGFpZ25JZCI6Im5vdGlmaWNhdGlvbnMuYXV0by4wUnd4aHVKREVlV19zUTV2X2ljMU13In19LCJ1c2VySWQiOi0xfQ.5r-qb5j366X5s3KAMNqkjS_E7MsB0RKkxWjxnGjUbOg> 
  | Please do not reply directly to this email
To no longer receive invitations from your friends on Coursera, 
Unsubscribe
<https://eventing.coursera.org/redirectSigned/eyJrZXkiOiJlbWFpbC5saW5rLm9wZW4iLCJ2YWx1ZSI6eyJ1cmwiOiJodHRwczovL3d3dy5jb3Vyc2VyYS5vcmcvYWNjb3VudC91bnN1YnNjcmliZS9UdWdsY3VkTmp0SE95WFAzZjQtZEZNODV6OGY5SXdyQ3lCbmtRTGhkSk9DVU1UOExiQUlTTktOaEhaZ3pkSUc4UVo1emVNOVRJdlRyXzQ1am0wMDlKUS55UTdTZk12TUxWUXI0NW1WODVmaUR3LnlkNHVURi0xREhQSGdJLXFKRERDbUlOaG9hSThTUE5XbWVHWWlWWlJ6NF94bF82ZkZRTTlWYWEzQVRUaFhNWFZab0FuRGxreHN0QXZjMWFWUXRsdUtmdjBXakRHWC1iOHlzWEVvZ2d2SUtiYUxsZEZfOEtTNjVBTDFwakRLMnJSbVhLZXViOV9CMjh0RnNjRzV5dGZrOGFnM0szUElnbDJEVjZldGFORks3ZnZYaS0zamtNdnJMLTR1UXFzcGRiQ0Exa0htZ3ZJQXVvaGcyTlRXSzV1T3Q3VU5oaURoTUoyakdFZmZQdFNNSmVPMkxYS3FkWF9udGFrRWR3UlotWjRqWmxuU1lEcWI3Z2owSTgzay1pSWlSa002SHhBWFhOcnJzRnJlZzIzd2xqNE1ZTU9Ia244OEpsSFg1ejBzMTNpP3V0bV9tZWRpdW09ZW1haWwmdXRtX3NvdXJjZT1pbnZpdGF0aW9ucyZ1dG1fY2FtcGFpZ249bm90aWZpY2F0aW9ucy5hdXRvLjBSd3hodUpERWVXX3NRNXZfaWMxTXciLCJ0cmFja2luZyI6eyJ1c2VySWQiOi0xLCJ1c2VyRW1haWwiOiJyZXBseSswMDgxYjBlODFhNTg2ODc4OGQ2ODc4M2JmMzk4ZjNlODIwNWEzODhlYTBiMDQ5MDM5MmNmMDAwMDAwMDExMTNhMzhlNTkyYTE2OWNlMDBiNGNmMzZAcmVwbHkuZ2l0aHViLmNvbSIsIm5vdGlmaWNhdGlvblR5cGUiOiJncm93dGguaW52aXRhdGlvbiIsImNhbXBhaWduSWQiOiJub3RpZmljYXRpb25zLmF1dG8uMFJ3eGh1SkRFZVdfc1E1dl9pYzFNdyJ9fSwidXNlcklkIjotMX0.lgWUgiguulMT7Ncs5mK0M7kYMqOBAIbEaBGjFaVrQnc>
Copyright © 2016, Coursera Inc. | 381 E. Evelyn Ave, Mountain View, CA 
94041 USA
