### ISSUE TITLE
Integrate ReverseForm

### ISSUE THREAD

**Issue by vgarvardt** [Danielss89/ZfcUserAdmin#27]
I want to suggest integrate [ReverseForm](https://github.com/silvester/ReverseForm) for form generation - it will make add/edit user form generation much easier to maintain. The only disadvantage it gives - additional requirement for module installation.

I can handle this issue by myself, but it would be nice if ZfcUserAdmin added this into root project because maintaining branch is not so funny =)

**Comment by Danielss89** [comment]
I'm not fund of making ZfcUserAdmin dependant on other modules.
