### ISSUE TITLE
Adding form elements extending editForm using event listener creates duplicates

### ISSUE THREAD

**Issue by webdevilopers** [Danielss89/ZfcUserAdmin#32]
```
class Module implements FormElementProviderInterface
{
    public function onBootstrap($e)
    {
        $em  = $app->getEventManager()->getSharedManager();

        $em->attach('ZfcUserAdmin\Form\EditUser', 'init', function($e) {
            // $form is a ZfcUser\Form\Register
            $form = $e->getTarget();

            $form->add(array(
                'name' => 'costCenters',
            'type' => 'select',
                'options' => array(
                    'label' => 'Cost centers',
                ),
            ));
        });
    }
}
```

This creates the **costcenters** element twice - the second one after the **userId** element.

This DOES NOT HAPPEN when using the same listener on the ''ZfcUserAdmin\Form\CreateUser*\* form.

Both forms share the same _form.phtml view.

**Comment by webdevilopers** [comment]
So far I can say that the event listener for **ZfcUserAdmin\Form\CreateUser** is called twice.

**Comment by webdevilopers** [comment]
The second call is caused by l. 75 of **ZfcUserAdmin\Form\EditUser**:

```
$this->getEventManager()->trigger('init', $this);
```

Can this line be removed?

**Comment by webdevilopers** [comment]
Looks like the line has moved to l. 71. in **ZfcUserAdmin\Form\EditUser**:

```
$this->getEventManager()->trigger('init', $this);
```

Still, can it be removed to prevent calling the event listener twice?

**Comment by webdevilopers** [comment]
Are you still working on this project, @Danielss89 ?

**Comment by Danielss89** [comment]
Not at this moment. PR's welcome.

**Comment by webdevilopers** [comment]
Sorry for the late reply, @yurevichcv fixed this issue successfully. 
Seems to have been merged to the current version.
Thanks.

Closing.
