### ISSUE TITLE
Pagination does not work out of the box

### ISSUE THREAD

**Issue by jjmoorhouse** [Danielss89/ZfcUserAdmin#34]
pagination does not work when first installing zfcuser admin

I have 'fixed' this for my fork of the repo by removing it, but perhaps there is a better solution/fix to the issue?

https://github.com/jjmoorhouse/ZfcUserAdmin/compare

**Comment by stijnhau** [comment]
Pagination does work but only with 100 elem,nt per page and not with 10 per page like said in view.
I created an issue for it yesterday (or the day before)
