### ISSUE TITLE
ZfcUserAdmin created a module under zendframework2 

### ISSUE THREAD

**Issue by bhagi123** [Danielss89/ZfcUserAdmin#40]
sir, my error below
Fatal error: Uncaught exception 'Zend\Mvc\Router\Exception\InvalidArgumentException' with message 'Missing "type" option' in D:\Program Files\Zend\ZendServer\data\libraries\Zend_Framework_2\2.2.1\library\Zend\Mvc\Router\SimpleRouteStack.php:269 Stack trace: #0 D:\Program Files\Zend\ZendServer\data\libraries\Zend_Framework_2\2.2.1\library\Zend\Mvc\Router\Http\TreeRouteStack.php(159): Zend\Mvc\Router\SimpleRouteStack->routeFromArray(Array) #1 D:\Program Files\Zend\ZendServer\data\libraries\Zend_Framework_2\2.2.1\library\Zend\Mvc\Router\Http\TreeRouteStack.php(113): Zend\Mvc\Router\Http\TreeRouteStack->routeFromArray(Array) #2 D:\Program Files\Zend\ZendServer\data\libraries\Zend_Framework_2\2.2.1\library\Zend\Mvc\Router\SimpleRouteStack.php(140): Zend\Mvc\Router\Http\TreeRouteStack->addRoute('zfcadmin', Array) #3 D:\Program Files\Zend\ZendServer\data\libraries\Zend_Framework_2\2.2.1\library\Zend\Mvc\Router\SimpleRouteStack.php(84): Zend\Mvc\Router\SimpleRouteStack->addRoutes(Array) #4 D:\Program Files\Zend\ZendServer\data\li in D:\Program Files\Zend\ZendServer\data\libraries\Zend_Framework_2\2.2.1\library\Zend\ServiceManager\ServiceManager.php on line 860

**Comment by barry1955** [comment]
Hi,
Did you get your problem resolved?

**Comment by bhagi123** [comment]
hello,
am onto something . i have stopped this module temporarily
