### ISSUE TITLE
Cant use module

### ISSUE THREAD

**Issue by stijnhau** [Danielss89/ZfcUserAdmin#44]
Hello

I can't add this module.
By composer it won't add because it isnt fully registerd by pacagist.(w<hich is because it is just a demo).
ZFC user-afcaAdmin are installed by composer from zf-commons
So added the hole folder to the vendor dir.
added 'ZfcBase',
        'ZfcUser',
        'ZfcAdmin',
        'ZfcUserAdmin' to the modules array in the aplication.config.php in autoload of project.
But i get:
( ! ) Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ZfcUserAdmin) could not be initialized.' in D:\Dropbox\server\Workspace\testProject\vendor\zendframework\zendframework\library\Zend\ModuleManager\ModuleManager.php on line 189
( ! ) Zend\ModuleManager\Exception\RuntimeException: Module (ZfcUserAdmin) could not be initialized. in D:\Dropbox\server\Workspace\testProject\vendor\zendframework\zendframework\library\Zend\ModuleManager\ModuleManager.php on line 189

**Comment by stijnhau** [comment]
Fixed isuue by using the @dev tag for composer to do the import

**Comment by Danielss89** [comment]
You could also add the repository to composer.json and use dev-master for 'tag'. Then it would go around packagist.
