### ISSUE TITLE
Fatal with lastets zfcUser

### ISSUE THREAD

**Issue by stijnhau** [Danielss89/ZfcUserAdmin#51]
Got this error when using the latest version of this module and the zfcUser

Catchable fatal error: Argument 1 passed to ZfcUser\Mapper\UserHydrator::__construct() must be an instance of Zend\Crypt\Password\PasswordInterface, none given, called in D:\Dropbox\server\Workspace\True-Life\vendor\danielss89\zfc-user-admin\config\services.config.php on line 92 and defined in D:\Dropbox\server\Workspace\True-Life\vendor\zf-commons\zfc-user\src\ZfcUser\Mapper\UserHydrator.php on line 21

**Comment by stijnhau** [comment]
Created a PR with the fix.

**Comment by stijnhau** [comment]
any progres on this one?

**Comment by xavisavvy** [comment]
Found the same on our server after swapping from the git module to composer package.

> ( ! ) Catchable fatal error: Argument 1 passed to ZfcUser\Mapper\UserHydrator::__construct() must be an instance of Zend\Crypt\Password\PasswordInterface, none given, called in /Users/x/www/x/module/Application/Module.php on line 492 and defined in /Users/x/www/x/vendor/zf-commons/zfc-user/src/ZfcUser/Mapper/UserHydrator.php on line 21

Update: After rolling back to 0.1.2 from dev/master it all started working fine. I believe it has something to do with running an older version of zf2, but i could be wrong. 

Here is my my current composer config for requirements. (to get it to break change zf-commons to dev/master)

```
"php" : ">=5.3.8",
"zendframework/zendframework" : "2.1.4",
"zendframework/zendservice-twitter" : "=2.1.0",
"zendframework/zend-db" : "=2.3.0",
"zf-commons/zfc-user": "0.1.2"
```

**Comment by stijnhau** [comment]
Indead.
But https://github.com/Danielss89/ZfcUserAdmin/pull/55 is even better work with ZfcUser1 and dev-master.
